### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by hezi12345** [umn-cris/hfplayer#2]
![1](https://user-images.githubusercontent.com/29906475/27847175-cf4eda9e-616e-11e7-9fe4-5d44f2ffc334.png)
![2](https://user-images.githubusercontent.com/29906475/27847215-f7dd8122-616e-11e7-93b1-51dc8b959996.png)

how to fix this problem ?

**Comment by libingzheren** [comment]
I think you lacks of libaio library in your system. If you use linux system, you can install it by "sudo apt-get install libaio1 libaio-dev_"

**Comment by hezi12345** [comment]
i install the tool under centos platform , now i install the libaio, it seems the problem attributed to the libboost-graph-dev,but the library can be installed in ubuntu directly,but not in centos ,so can anyone  find the libboost-graph-dev for me ?aha@
